package main

import (
	"syscall/js"
)

func main() {
	c := make(chan struct{})
	js.Global().Set("gethtml", js.FuncOf(gethtml))
	js.Global().Set("getjs", js.FuncOf(getJavaScript))
	<-c
}

func gethtml(this js.Value, args []js.Value) interface{} {
	html := `
		<!DOCTYPE html>
		<html lang="en">
		<head>
			<meta charset="UTF-8">
			<title>Generated by WASM</title>
		</head>
		<body>
			<h1>Hello from WebAssembly!</h1>
		</body>
		</html>
	`
	return html
}
func getJavaScript(this js.Value, args []js.Value) interface{} {
	jsCode := `
		function sayHello() {
			alert('Hello from generated JavaScript!');
		}
	`
	return jsCode
}
